#!/usr/bin/env python3
"""
Implement improved Monthly Projections:
1. Checkboxes to mark investment done for each month
2. Horizontal table layout (one month per row, all funds in columns)
3. Show only current year data (archive previous years)
4. Live data ONLY for checked months, projected for unchecked
"""

print("🔧 Implementing improved monthly tracking...")
print("=" * 70)

with open('index.html', 'r') as f:
    html = f.read()

# Step 1: Update the Monthly Projections page structure
print("\n📋 Step 1: Updating Monthly Projections page structure...")

# Find the monthly table section for "your" portfolio
old_monthly_section = '''    <div class="sh"><span class="sh-n">03</span><h2>Your Portfolio - Month-by-Month Projection</h2></div>
    <div class="alert warning" style="margin-bottom:16px">📝 <strong>LUMP SUM:</strong> Click any "Lump Sum" cell to add one-time investments for that month/fund. Calculations update automatically.</div>
    <div class="tw" style="margin-bottom:32px">
      <table id="yourMonthlyTable">
        <thead>
          <tr>
            <th>Month</th>
            <th>Fund</th>
            <th>SIP</th>
            <th>Lump Sum</th>
            <th>Total Invested</th>
            <th>NAV</th>
            <th>Units</th>
            <th>Value</th>
            <th>Correction %</th>
          </tr>
        </thead>
        <tbody id="yourMonthlyTableBody">
          <!-- Generated by JavaScript -->
        </tbody>
      </table>
    </div>'''

new_monthly_section = '''    <div class="sh"><span class="sh-n">03</span><h2>Your Portfolio - Month-by-Month Tracking (Current Year Only)</h2></div>
    <div class="alert warning" style="margin-bottom:16px">
      ✅ <strong>HOW TO USE:</strong><br>
      • Check the box when you've completed that month's investment<br>
      • Checked months = LIVE data from market (actual NAV, units, value)<br>
      • Unchecked months = PROJECTED data (anticipated values)<br>
      • Click any Lump Sum to add one-time investments<br>
      • Previous years are archived automatically
    </div>
    
    <div style="margin-bottom:16px;display:flex;gap:12px;align-items:center">
      <label style="font-size:13px;font-weight:600">Showing Year:</label>
      <select id="yourYearSelector" onchange="changeYearView('your', this.value)" style="background:var(--bg3);border:1px solid var(--border);color:var(--you);padding:8px 12px;border-radius:4px;font-family:monospace">
        <option value="2026">2026</option>
        <option value="2027">2027</option>
        <option value="2028">2028</option>
        <option value="2029">2029</option>
        <option value="2030">2030</option>
      </select>
      <span id="yourArchiveNote" style="font-size:11px;color:var(--ink3);margin-left:8px"></span>
    </div>
    
    <div class="tw" style="margin-bottom:32px;overflow-x:auto">
      <table id="yourMonthlyTable" style="font-size:11px">
        <thead>
          <tr>
            <th style="min-width:40px">✓</th>
            <th style="min-width:80px">Month</th>
            <th colspan="7" style="background:rgba(240,180,41,0.1);border-left:2px solid var(--you)">Fund 1: Parag Parikh Flexi Cap</th>
            <th colspan="7" style="background:rgba(48,200,122,0.05)">Fund 2: Nifty 50 Index</th>
            <th colspan="7" style="background:rgba(240,180,41,0.05)">Fund 3: Motilal Midcap</th>
            <th colspan="7" style="background:rgba(48,200,122,0.05)">Fund 4: Quant Small Cap</th>
            <th colspan="7" style="background:rgba(240,180,41,0.05)">Fund 5: HDFC Balanced Adv</th>
            <th colspan="7" style="background:rgba(48,200,122,0.05)">Fund 6: Nifty Next 50</th>
            <th colspan="7" style="background:rgba(240,180,41,0.05)">Fund 7: NPS Tier 1</th>
            <th colspan="7" style="background:rgba(48,200,122,0.05);border-right:2px solid var(--you)">Fund 8: HDFC Liquid</th>
          </tr>
          <tr style="font-size:10px">
            <th></th>
            <th></th>
            <th>SIP</th><th>Lump</th><th>Invested</th><th>NAV</th><th>Units</th><th>Value</th><th>Corr%</th>
            <th>SIP</th><th>Lump</th><th>Invested</th><th>NAV</th><th>Units</th><th>Value</th><th>Corr%</th>
            <th>SIP</th><th>Lump</th><th>Invested</th><th>NAV</th><th>Units</th><th>Value</th><th>Corr%</th>
            <th>SIP</th><th>Lump</th><th>Invested</th><th>NAV</th><th>Units</th><th>Value</th><th>Corr%</th>
            <th>SIP</th><th>Lump</th><th>Invested</th><th>NAV</th><th>Units</th><th>Value</th><th>Corr%</th>
            <th>SIP</th><th>Lump</th><th>Invested</th><th>NAV</th><th>Units</th><th>Value</th><th>Corr%</th>
            <th>SIP</th><th>Lump</th><th>Invested</th><th>NAV</th><th>Units</th><th>Value</th><th>Corr%</th>
            <th>SIP</th><th>Lump</th><th>Invested</th><th>NAV</th><th>Units</th><th>Value</th><th>Corr%</th>
          </tr>
        </thead>
        <tbody id="yourMonthlyTableBody">
          <!-- Generated by JavaScript -->
        </tbody>
      </table>
    </div>'''

html = html.replace(old_monthly_section, new_monthly_section)
print("   ✅ Updated YOUR portfolio table structure")

# Do the same for wife's portfolio
old_wife_section = '''    <div class="sh"><span class="sh-n">06</span><h2>Wife's Portfolio - Month-by-Month Projection</h2></div>
    <div class="tw">
      <table id="wifeMonthlyTable">
        <thead>
          <tr>
            <th>Month</th>
            <th>Fund</th>
            <th>SIP</th>
            <th>Lump Sum</th>
            <th>Total Invested</th>
            <th>NAV</th>
            <th>Units</th>
            <th>Value</th>
            <th>Correction %</th>
          </tr>
        </thead>
        <tbody id="wifeMonthlyTableBody">
          <!-- Generated by JavaScript -->
        </tbody>
      </table>
    </div>'''

new_wife_section = '''    <div class="sh"><span class="sh-n">06</span><h2>Wife's Portfolio - Month-by-Month Tracking (Current Year Only)</h2></div>
    
    <div style="margin-bottom:16px;display:flex;gap:12px;align-items:center">
      <label style="font-size:13px;font-weight:600">Showing Year:</label>
      <select id="wifeYearSelector" onchange="changeYearView('wife', this.value)" style="background:var(--bg3);border:1px solid var(--border);color:var(--wife);padding:8px 12px;border-radius:4px;font-family:monospace">
        <option value="2026">2026</option>
        <option value="2027">2027</option>
        <option value="2028">2028</option>
        <option value="2029">2029</option>
        <option value="2030">2030</option>
      </select>
      <span id="wifeArchiveNote" style="font-size:11px;color:var(--ink3);margin-left:8px"></span>
    </div>
    
    <div class="tw" style="overflow-x:auto">
      <table id="wifeMonthlyTable" style="font-size:11px">
        <thead>
          <tr>
            <th style="min-width:40px">✓</th>
            <th style="min-width:80px">Month</th>
            <th colspan="7" style="background:rgba(224,64,160,0.1);border-left:2px solid var(--wife)">Fund 1: ICICI Bluechip</th>
            <th colspan="7" style="background:rgba(224,64,160,0.05);border-right:2px solid var(--wife)">Fund 2: Axis Midcap</th>
          </tr>
          <tr style="font-size:10px">
            <th></th>
            <th></th>
            <th>SIP</th><th>Lump</th><th>Invested</th><th>NAV</th><th>Units</th><th>Value</th><th>Corr%</th>
            <th>SIP</th><th>Lump</th><th>Invested</th><th>NAV</th><th>Units</th><th>Value</th><th>Corr%</th>
          </tr>
        </thead>
        <tbody id="wifeMonthlyTableBody">
          <!-- Generated by JavaScript -->
        </tbody>
      </table>
    </div>'''

html = html.replace(old_wife_section, new_wife_section)
print("   ✅ Updated WIFE's portfolio table structure")

# Step 2: Add JavaScript for checkbox tracking and year filtering
print("\n⚙️  Step 2: Adding checkbox tracking and year filtering...")

script_end = html.rfind('</script>')

new_tracking_js = '''
// ============================================
// MONTHLY TRACKING - CHECKBOXES & YEAR FILTER
// ============================================

// Store which months are marked as "invested"
let yourInvestedMonths = {}; // { 'YYYY-MM': true/false }
let wifeInvestedMonths = {};

// Current year being viewed
let yourCurrentYear = 2026;
let wifeCurrentYear = 2026;

// Load invested months from localStorage
function loadInvestedMonths() {
  const yourSaved = localStorage.getItem('yourInvestedMonths');
  const wifeSaved = localStorage.getItem('wifeInvestedMonths');
  
  if (yourSaved) yourInvestedMonths = JSON.parse(yourSaved);
  if (wifeSaved) wifeInvestedMonths = JSON.parse(wifeSaved);
  
  console.log('Loaded invested months:', { your: yourInvestedMonths, wife: wifeInvestedMonths });
}

// Save invested months to localStorage
function saveInvestedMonths() {
  localStorage.setItem('yourInvestedMonths', JSON.stringify(yourInvestedMonths));
  localStorage.setItem('wifeInvestedMonths', JSON.stringify(wifeInvestedMonths));
  console.log('Saved invested months');
}

// Toggle month invested status
function toggleMonthInvested(portfolio, monthKey) {
  const investedMonths = portfolio === 'your' ? yourInvestedMonths : wifeInvestedMonths;
  
  investedMonths[monthKey] = !investedMonths[monthKey];
  saveInvestedMonths();
  
  console.log(`Toggled ${portfolio} ${monthKey}: ${investedMonths[monthKey]}`);
  
  // Re-render to update live/projected data
  renderMonthlyTable(portfolio, portfolio === 'your' ? yourFunds : wifeFunds, 
                     portfolio === 'your' ? yourLumpSums : wifeLumpSums);
}

// Change year view
function changeYearView(portfolio, year) {
  if (portfolio === 'your') {
    yourCurrentYear = parseInt(year);
  } else {
    wifeCurrentYear = parseInt(year);
  }
  
  console.log(`Changed ${portfolio} year view to ${year}`);
  
  // Re-render table for selected year
  renderMonthlyTable(portfolio, portfolio === 'your' ? yourFunds : wifeFunds,
                     portfolio === 'your' ? yourLumpSums : wifeLumpSums);
}

// Get months for a specific year
function getMonthsForYear(year) {
  const months = [];
  for (let m = 0; m < 12; m++) {
    const date = new Date(year, m, 1);
    const monthKey = date.toISOString().substring(0, 7); // YYYY-MM
    const displayDate = date.toLocaleDateString('en-US', { year: 'numeric', month: 'short' });
    months.push({ key: monthKey, display: displayDate, date: date });
  }
  return months;
}

// Check if month is in the past (investment should be done)
function isMonthPast(monthKey) {
  const now = new Date();
  const currentMonthKey = now.toISOString().substring(0, 7);
  return monthKey < currentMonthKey;
}

'''

html = html[:script_end] + new_tracking_js + html[script_end:]
print("   ✅ Added checkbox and year filtering JavaScript")

# Step 3: Update renderMonthlyTable function
print("\n🎨 Step 3: Updating renderMonthlyTable function...")

# Find and replace the renderMonthlyTable function
old_render_table_start = '''function renderMonthlyTable(portfolio, funds, lumpSums) {
  const tbody = document.getElementById(`${portfolio}MonthlyTableBody`);
  if (!tbody) return;
  
  tbody.innerHTML = '';
  
  const startDate = new Date('2026-04-01');
  const retirementDate = new Date('2054-12-31');

  // Investment starts April 2026 - show from that date
  const displayStartDate = new Date('2026-04-01');
  
  funds.forEach((fund, fundIdx) => {
    const monthsData = calculateMonthlyProjection(fund, displayStartDate, retirementDate, lumpSums[fundIdx] || {});
    
    // Show first 24 months only
    monthsData.slice(0, 24).forEach((month, monthIdx) => {
      const row = document.createElement('tr');
      
      row.innerHTML = `
        <td>${month.displayDate}</td>
        <td style="font-size:11px">${fund.name.substring(0, 30)}...</td>
        <td class="text-right">₹${(month.sip / 1000).toFixed(1)}K</td>
        <td class="text-right">
          <input type="number" value="${month.lumpSum}" 
                 onchange="updateLumpSum('${portfolio}', ${fundIdx}, '${month.date}', this.value)"
                 style="width:80px;background:var(--bg3);border:1px solid var(--border);color:var(--you);padding:4px;border-radius:3px;text-align:right;font-size:11px">
        </td>
        <td class="text-right">₹${(month.totalInvested / 100000).toFixed(2)}L</td>
        <td class="text-right">₹${month.nav}</td>
        <td class="text-right">${parseFloat(month.units).toFixed(2)}</td>
        <td class="text-right">₹${(month.value / 100000).toFixed(2)}L</td>
        <td class="text-right" style="color:${month.correction >= 0 ? 'var(--jt)' : 'var(--red)'}">${month.correction >= 0 ? '+' : ''}${month.correction}%</td>
      `;
      
      tbody.appendChild(row);
    });
  });
}'''

new_render_table = '''function renderMonthlyTable(portfolio, funds, lumpSums) {
  const tbody = document.getElementById(`${portfolio}MonthlyTableBody`);
  if (!tbody) return;
  
  tbody.innerHTML = '';
  
  const investedMonths = portfolio === 'your' ? yourInvestedMonths : wifeInvestedMonths;
  const currentYear = portfolio === 'your' ? yourCurrentYear : wifeCurrentYear;
  
  // Get months for selected year
  const yearMonths = getMonthsForYear(currentYear);
  
  // Filter to only show from April 2026 onwards
  const validMonths = yearMonths.filter(m => m.key >= '2026-04');
  
  // Calculate data for all funds for this year
  const allFundsData = funds.map((fund, fundIdx) => {
    const monthsData = calculateMonthlyProjection(fund, new Date('2026-04-01'), new Date(`${currentYear}-12-31`), lumpSums[fundIdx] || {});
    return monthsData;
  });
  
  // Render one row per month (horizontal layout)
  validMonths.forEach(monthInfo => {
    const row = document.createElement('tr');
    
    const isInvested = investedMonths[monthInfo.key] || false;
    const isPast = isMonthPast(monthInfo.key);
    
    let rowHTML = `
      <td style="text-align:center">
        <input type="checkbox" ${isInvested ? 'checked' : ''} 
               onchange="toggleMonthInvested('${portfolio}', '${monthInfo.key}')"
               style="cursor:pointer;width:16px;height:16px">
      </td>
      <td style="font-weight:600">${monthInfo.display}</td>
    `;
    
    // Add data for each fund
    funds.forEach((fund, fundIdx) => {
      // Find this month's data for this fund
      const fundMonthsData = allFundsData[fundIdx];
      const monthData = fundMonthsData.find(m => m.date === monthInfo.key);
      
      if (monthData) {
        const dataType = isInvested ? 'LIVE' : 'PROJ';
        const bgColor = isInvested ? 'rgba(48,200,122,0.05)' : 'rgba(255,255,255,0.02)';
        
        rowHTML += `
          <td class="text-right" style="background:${bgColor};font-size:10px">₹${(monthData.sip / 1000).toFixed(1)}K</td>
          <td class="text-right" style="background:${bgColor}">
            <input type="number" value="${monthData.lumpSum}" 
                   onchange="updateLumpSum('${portfolio}', ${fundIdx}, '${monthInfo.key}', this.value)"
                   style="width:60px;background:var(--bg3);border:1px solid var(--border);color:var(--you);padding:2px 4px;border-radius:2px;text-align:right;font-size:10px">
          </td>
          <td class="text-right" style="background:${bgColor};font-size:10px">₹${(monthData.totalInvested / 100000).toFixed(2)}L</td>
          <td class="text-right" style="background:${bgColor};font-size:10px;${isInvested ? 'font-weight:700;color:var(--jt)' : ''}">₹${monthData.nav}</td>
          <td class="text-right" style="background:${bgColor};font-size:10px">${parseFloat(monthData.units).toFixed(2)}</td>
          <td class="text-right" style="background:${bgColor};font-size:10px;${isInvested ? 'font-weight:700' : ''}">₹${(monthData.value / 100000).toFixed(2)}L</td>
          <td class="text-right" style="background:${bgColor};font-size:10px;color:${monthData.correction >= 0 ? 'var(--jt)' : 'var(--red)'}">${monthData.correction >= 0 ? '+' : ''}${monthData.correction}%</td>
        `;
      } else {
        // No data for this month
        rowHTML += '<td colspan="7" style="text-align:center;color:var(--ink3);font-size:10px">-</td>';
      }
    });
    
    row.innerHTML = rowHTML;
    tbody.appendChild(row);
  });
  
  // Update archive note
  const archiveNote = document.getElementById(`${portfolio}ArchiveNote`);
  if (archiveNote) {
    const archivedYears = [];
    for (let y = 2026; y < currentYear; y++) {
      archivedYears.push(y);
    }
    if (archivedYears.length > 0) {
      archiveNote.textContent = `📦 Archived: ${archivedYears.join(', ')}`;
    } else {
      archiveNote.textContent = '';
    }
  }
}'''

html = html.replace(old_render_table_start, new_render_table)
print("   ✅ Updated renderMonthlyTable with horizontal layout and checkboxes")

# Step 4: Update initialization to load invested months
print("\n🔄 Step 4: Updating initialization...")

old_render_call = '''async function renderMonthlyProjections() {
  console.log('Rendering monthly projections...');
  
  // Load NAVs first
  await loadAllNAVs();'''

new_render_call = '''async function renderMonthlyProjections() {
  console.log('Rendering monthly projections...');
  
  // Load invested months from localStorage
  loadInvestedMonths();
  
  // Load NAVs first
  await loadAllNAVs();'''

html = html.replace(old_render_call, new_render_call)
print("   ✅ Updated initialization to load invested months")

# Write output
with open('index.html', 'w') as f:
    f.write(html)

print("\n" + "=" * 70)
print("✅ MONTHLY TRACKING IMPROVEMENTS COMPLETE!")
print("=" * 70)
print("\n🎯 NEW FEATURES:")
print("   ✅ Checkboxes: Mark when month's investment is done")
print("   ✅ Live vs Projected: Checked = LIVE data, Unchecked = PROJECTED")
print("   ✅ Horizontal Layout: One month per row, all funds in columns")
print("   ✅ Year Selector: Show only current year, archive old years")
print("   ✅ Visual Distinction: Live data highlighted with green tint")
print("")
print("📊 TABLE STRUCTURE:")
print("   Row: Month (e.g., Apr 2026)")
print("   Columns: Fund1 (SIP/Lump/Inv/NAV/Units/Value/Corr%) | Fund2 ... | Fund8")
print("")
print("💡 HOW IT WORKS:")
print("   • April 2026 - Current Month: Show in table")
print("   • Check box when you complete investment")
print("   • Checked months: Fetch LIVE NAV and calculate actual units/value")
print("   • Unchecked months: Show PROJECTED values")
print("   • Change year dropdown to view 2026, 2027, 2028, etc.")
print("   • Previous years automatically archived")

